version: "3.8"
services:
    cgi:
        container_name: cgi
        build: .
        volumes:
            - ./src:/var/www/html
            - ./mount:/data
        ports:
            - 8000:80
        env_file: .env
        # depends_on:
        #     - db
    # db:
    #     container_name: db
    #     image: mysql
    #     restart: always
    #     env_file: env/mysql
    #     ports:
    #         - 8001:3306
    #     volumes:
    #         - ./mount/mysql:/var/lib/mysql
    # phpmyadmin:
    #     container_name: phpmyadmin
    #     image: phpmyadmin/phpmyadmin
    #     ports:
    #         - 8002:80
    #     restart: always
    #     environment:
    #         PMA_HOST: db
    #     depends_on:
    #         - db
