version: "3.8"
services:
    cgi:
        container_name: cgi
        image: php:8.0-apache
        volumes:
            - ./php:/var/www/html
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        env_file: env/mysql
        ports:
            - 8001:3306
        volumes:
            - ./mount/mysql:/var/lib/mysql
